#!/usr/bin/env python
import code

def show(input):
    lines = iter(input.splitlines())

    def readline(prompt):
        try:
            command = next(lines)
        except StopIteration:
            raise EOFError()
        print(prompt, command)
        return command

    code.interact(banner='', readfunc=readline)

import sys
if __name__=="__main__":
    show(open(sys.argv[1]).read())
